package validate

// iso4217 is the set of active ISO 4217 alphabetic currency codes.
// Source: ISO 4217 maintenance agency list (as of 2024).
var iso4217 = map[string]bool{
	"AED": true, "AFN": true, "ALL": true, "AMD": true, "ANG": true,
	"AOA": true, "ARS": true, "AUD": true, "AWG": true, "AZN": true,
	"BAM": true, "BBD": true, "BDT": true, "BGN": true, "BHD": true,
	"BIF": true, "BMD": true, "BND": true, "BOB": true, "BOV": true,
	"BRL": true, "BSD": true, "BTN": true, "BWP": true, "BYN": true,
	"BZD": true, "CAD": true, "CDF": true, "CHE": true, "CHF": true,
	"CHW": true, "CLF": true, "CLP": true, "CNY": true, "COP": true,
	"COU": true, "CRC": true, "CUC": true, "CUP": true, "CVE": true,
	"CZK": true, "DJF": true, "DKK": true, "DOP": true, "DZD": true,
	"EGP": true, "ERN": true, "ETB": true, "EUR": true, "FJD": true,
	"FKP": true, "GBP": true, "GEL": true, "GHS": true, "GIP": true,
	"GMD": true, "GNF": true, "GTQ": true, "GYD": true, "HKD": true,
	"HNL": true, "HTG": true, "HUF": true, "IDR": true, "ILS": true,
	"INR": true, "IQD": true, "IRR": true, "ISK": true, "JMD": true,
	"JOD": true, "JPY": true, "KES": true, "KGS": true, "KHR": true,
	"KMF": true, "KPW": true, "KRW": true, "KWD": true, "KYD": true,
	"KZT": true, "LAK": true, "LBP": true, "LKR": true, "LRD": true,
	"LSL": true, "LYD": true, "MAD": true, "MDL": true, "MGA": true,
	"MKD": true, "MMK": true, "MNT": true, "MOP": true, "MRU": true,
	"MUR": true, "MVR": true, "MWK": true, "MXN": true, "MXV": true,
	"MYR": true, "MZN": true, "NAD": true, "NGN": true, "NIO": true,
	"NOK": true, "NPR": true, "NZD": true, "OMR": true, "PAB": true,
	"PEN": true, "PGK": true, "PHP": true, "PKR": true, "PLN": true,
	"PYG": true, "QAR": true, "RON": true, "RSD": true, "RUB": true,
	"RWF": true, "SAR": true, "SBD": true, "SCR": true, "SDG": true,
	"SEK": true, "SGD": true, "SHP": true, "SLE": true, "SOS": true,
	"SRD": true, "SSP": true, "STN": true, "SVC": true, "SYP": true,
	"SZL": true, "THB": true, "TJS": true, "TMT": true, "TND": true,
	"TOP": true, "TRY": true, "TTD": true, "TWD": true, "TZS": true,
	"UAH": true, "UGX": true, "USD": true, "USN": true, "UYI": true,
	"UYU": true, "UYW": true, "UZS": true, "VED": true, "VES": true,
	"VND": true, "VUV": true, "WST": true, "XAF": true, "XAG": true,
	"XAU": true, "XBA": true, "XBB": true, "XBC": true, "XBD": true,
	"XCD": true, "XDR": true, "XOF": true, "XPD": true, "XPF": true,
	"XPT": true, "XSU": true, "XTS": true, "XUA": true, "XXX": true,
	"YER": true, "ZAR": true, "ZMW": true, "ZWL": true,
}

// iso3166alpha2 is the set of ISO 3166-1 alpha-2 country codes.
// Source: ISO 3166 maintenance agency (as of 2024).
var iso3166alpha2 = map[string]bool{
	"AD": true, "AE": true, "AF": true, "AG": true, "AI": true,
	"AL": true, "AM": true, "AO": true, "AQ": true, "AR": true,
	"AS": true, "AT": true, "AU": true, "AW": true, "AX": true,
	"AZ": true, "BA": true, "BB": true, "BD": true, "BE": true,
	"BF": true, "BG": true, "BH": true, "BI": true, "BJ": true,
	"BL": true, "BM": true, "BN": true, "BO": true, "BQ": true,
	"BR": true, "BS": true, "BT": true, "BV": true, "BW": true,
	"BY": true, "BZ": true, "CA": true, "CC": true, "CD": true,
	"CF": true, "CG": true, "CH": true, "CI": true, "CK": true,
	"CL": true, "CM": true, "CN": true, "CO": true, "CR": true,
	"CU": true, "CV": true, "CW": true, "CX": true, "CY": true,
	"CZ": true, "DE": true, "DJ": true, "DK": true, "DM": true,
	"DO": true, "DZ": true, "EC": true, "EE": true, "EG": true,
	"EH": true, "ER": true, "ES": true, "ET": true, "FI": true,
	"FJ": true, "FK": true, "FM": true, "FO": true, "FR": true,
	"GA": true, "GB": true, "GD": true, "GE": true, "GF": true,
	"GG": true, "GH": true, "GI": true, "GL": true, "GM": true,
	"GN": true, "GP": true, "GQ": true, "GR": true, "GS": true,
	"GT": true, "GU": true, "GW": true, "GY": true, "HK": true,
	"HM": true, "HN": true, "HR": true, "HT": true, "HU": true,
	"ID": true, "IE": true, "IL": true, "IM": true, "IN": true,
	"IO": true, "IQ": true, "IR": true, "IS": true, "IT": true,
	"JE": true, "JM": true, "JO": true, "JP": true, "KE": true,
	"KG": true, "KH": true, "KI": true, "KM": true, "KN": true,
	"KP": true, "KR": true, "KW": true, "KY": true, "KZ": true,
	"LA": true, "LB": true, "LC": true, "LI": true, "LK": true,
	"LR": true, "LS": true, "LT": true, "LU": true, "LV": true,
	"LY": true, "MA": true, "MC": true, "MD": true, "ME": true,
	"MF": true, "MG": true, "MH": true, "MK": true, "ML": true,
	"MM": true, "MN": true, "MO": true, "MP": true, "MQ": true,
	"MR": true, "MS": true, "MT": true, "MU": true, "MV": true,
	"MW": true, "MX": true, "MY": true, "MZ": true, "NA": true,
	"NC": true, "NE": true, "NF": true, "NG": true, "NI": true,
	"NL": true, "NO": true, "NP": true, "NR": true, "NU": true,
	"NZ": true, "OM": true, "PA": true, "PE": true, "PF": true,
	"PG": true, "PH": true, "PK": true, "PL": true, "PM": true,
	"PN": true, "PR": true, "PS": true, "PT": true, "PW": true,
	"PY": true, "QA": true, "RE": true, "RO": true, "RS": true,
	"RU": true, "RW": true, "SA": true, "SB": true, "SC": true,
	"SD": true, "SE": true, "SG": true, "SH": true, "SI": true,
	"SJ": true, "SK": true, "SL": true, "SM": true, "SN": true,
	"SO": true, "SR": true, "SS": true, "ST": true, "SV": true,
	"SX": true, "SY": true, "SZ": true, "TC": true, "TD": true,
	"TF": true, "TG": true, "TH": true, "TJ": true, "TK": true,
	"TL": true, "TM": true, "TN": true, "TO": true, "TR": true,
	"TT": true, "TV": true, "TW": true, "TZ": true, "UA": true,
	"UG": true, "UM": true, "US": true, "UY": true, "UZ": true,
	"VA": true, "VC": true, "VE": true, "VG": true, "VI": true,
	"VN": true, "VU": true, "WF": true, "WS": true, "YE": true,
	"YT": true, "ZA": true, "ZM": true, "ZW": true,
}
